name: CD

on:
  push:
    branches: [master, dev]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          #TODO: how can i get the vrsion from the go.mod file?
          go-version: '1.26'
      - name: build app bin
        run: scripts/buildprod.sh
        # set up gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI to build and deploy'
        run: 'gcloud builds submit --tag
          us-east4-docker.pkg.dev/notely-boot-dev-494920/notely-bootdev/notely_bin:latest'
