name: CD

on:
  push:
    branches: [master, dev]
defaults:
  run:
    shell: bash
    working-directory: ./notely
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          #TODO: how can i get the vrsion from the go.mod file?
          go-version: '1.26'

      - name: build app bin
        run: ./scripts/buildprod.sh
